#
# Makefile for Linux's XIA stack.
#

obj-$(CONFIG_XIA) += xia.o

xia-objs :=	af_xia.o raw.o dag.o fib.o fib_frontend.o route.o

obj-$(CONFIG_XIA_PPAL_AD) += ppal_ad/
obj-$(CONFIG_XIA_PPAL_HID) += ppal_hid/
